version: '3'
services:
  categories-server:
    build: ../
    command: npm run start
    volumes:
      - ../:/usr/src/app
      - ../../protos:/usr/src/app/protos
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - DB_URL=mongodb://workplacex-db/workplacex
    ports:
      - "50052:50051"
    links:
      - workplacex-db:mongo
    depends_on:
      - workplacex-db
  workplacex-db:
    image: mongo
    ports:
      - "27017:27017"
