version: '3'
services:
  rest-gateway:
    build: ../
    command: npm run start
    volumes:
      - ../:/usr/src/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    external_links:
      - docker_items-server_1:items-server
    networks:
      - default
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=http://0.0.0.0:3000/api-docs.json
    ports:
      - 8080:8080
networks:
  default:
    external:
      name: docker_default