version: '3'
services:
  wpx_client-gateway:
    image: node:8.4
    build: ../
    command: npm run start
    volumes:
      - ../:/usr/src/app
      - ../../protos:/usr/src/app/protos
    environment:
      - NODE_ENV=development
      - DEBUG=true
    ports:
      - "3000:3000"
    external_links:
      - dkr_wpx_items-server_1:items-server
      - dkr_wpx_filters-server_1:filters-server
    networks:
      - wpx
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=http://0.0.0.0:3000/api-docs.json
    ports:
      - 8080:8080
networks:
  wpx:
    external:
      name: dkr_wpx