apiVersion: v1
kind: Service
metadata:
  name: client-gateway
  namespace: default
  labels:
    name: client-gateway
    type: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    name: client-gateway
    type: api
