apiVersion: v1
kind: Service
metadata:
  name: wishlists-server
  namespace: default
  labels:
    name: wishlists-server
    type: backend
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50051
  selector:
    name: wishlists-server
    type: backend
